(function(n){function u(m){var c=this;this.version="1.0.39";this.e=m;this.i={};this.d={};this.F={};this.ea={};this.q=new E(this);this.H=new I(this);this.p=[];this.v={};this.K={};this.h={};this.r={};this.j=!1;this.Ba=parseInt(J||200,10);this.Ha=this.na();this.e.displayAd=function(b,d,a,k,e){c.F[b]=k;c.ea[b]=!0;var f=e;e||(f=c.u(b,d,a));c.o(b)&&c.d&&f&&!c.da(f)&&(f.k&&f.k.length&&c.va(k),c.q.Y(f,!1,k)&&(c.ba(!0,f),c.H.ga(f)))};this.ma=this.e.displayAd;this.va=function(b){var d=A(b),a=d.s;b=d.ha;
a.getElementById(B)||(d=a.createElement("iframe"),d.style.cssText="position:absolute;left:-1000px;top:-1000px;border:0 solid;width:0;height:0;",d.width=d.height=0,d.name=B,d.id=B,d.src=F+K+"#"+b.location.protocol+"//"+b.location.host,a.body.appendChild(d),c.Ea=c.onPassbackReceived=function(a){var e,d=a.id,d=d&&d.replace("fif_slot_"+q+"_","");if((e=c.u(d))&&e.k&&e.k.length&&c.da(e)){try{a.id=a.name="dead_"+a.name;a.style.cssText="border:none;position:absolute;width:0;height:0;left:-10000px;top:-10000px;";
var g=a.contentWindow;g.name=a.id;g&&g.document&&"complete"===g.document.readyState&&a.parentNode&&a.parentNode.removeChild(a)}catch(h){n.__ASL_DEBUG&&console.error(h)}a=e.k.shift();e.V&&((new Image).src=e.V);a.noad_url&&((new Image).src=a.noad_url);e=c.X(a,d,e.C,e.b,e.k);c.q.Y(e,!0,b);c.H.ga(e)}},b[v]||(b[v]=c),c.q.n(b,"message",function(a){if(a.origin===F&&a.source){a=a.source;for(var d=a.parent;d!==b&&d!==b.top;)a=d,d=d.parent;if(a&&d===b)try{c.Ea(a.frameElement)}catch(f){s("No access to iframe from postMessage "+
f)}}},!1,b))};this.e.processDmp=function(b){c.isArray(b)&&(c.p=b);c.U()};this.processDmp=this.e.processDmp;this.Aa=function(){this.dmpSegCookieName=G;if(C&&!this.j){var b=("https:"===document.location.protocol?"https:":"http:")+C,d=document.createElement("script"),a=document.getElementsByTagName("script")[0];d.type="text/javascript";d.src=b;d.async=!0;c.j=setTimeout(c.U.bind(c),c.Ba);-1!==navigator.userAgent.indexOf("Opera")?setTimeout(function(){a.parentNode.insertBefore(d,a)},0):a.parentNode.insertBefore(d,
a);n.__putPixel(300400)}};this.Ia=function(){var b=this.e&&this.e.stack||{},d;for(d in b)b.hasOwnProperty(d+"")&&(this.aa(b[d]),delete b[d])};this.Ja=function(b,d){if("object"===typeof b&&b.hasOwnProperty("sectionId")&&c.isArray(d)){for(var a,k,e={},f,g=d.length;g--;)f=d[g],k=c.Ga(f.adUnitCode),a=x(k[1],k[2]),f.bidder&&(e[a]||(e[a]={P:[],O:[],Q:[],m:{}}),e[a].P.push(f.bidder),e[a].O.push(f.cpm||0),e[a].Q.push(k[0]),e[a].m[f.adUnitCode]=f);for(var h in e)e.hasOwnProperty(h)&&(this.h[h]={la:{hb_partner:e[h].P.join(","),
hb_bid:e[h].O.join(","),hb_slot_id:e[h].Q.join(",")},m:e[h].m})}};this.v=this.e&&this.e.globalCustomParams||{};this.setGlobalCustomParams=function(b){this.v=b||{}};this.aa=this.requestAds=function(b){b=b||{};b.dmp=!!C&&("undefined"===typeof b.dmp||!!b.dmp);b.cleanup&&c.ka(b);this.Ja(b,b.hbWinningBids);var d=x(b.sectionId,b.instance);if(!c.H.wa(d,b)&&!this.c[d]){delete c.i[d];delete c.d[d];if(c.h[d]){b.custom=b.custom||{};var a=c.h[d].la;b.custom.hb_partner=a.hb_partner;b.custom.hb_bid=a.hb_bid;b.custom.hb_slot_id=
a.hb_slot_id}this.c[d]=b;b.dmp&&c.j?(s("set callback"),b.sync=!1,c.r[d]=c.$.bind(c,b)):(b.dmp&&s("make a call"),this.$(b))}};this.ka=this.e.cleanup=function(b){b=x(b.sectionId,b.instance);var d=c.d[b],a=c.c[b];if(d&&a){var k=A(a.__window).s,e;for(e in d)if(d.hasOwnProperty(e)&&(c.ba(!1,d[e]),a=k.getElementById(e))){for(;a.firstChild;)try{a.removeChild(a.firstChild)}catch(f){}a.innerHTML="";a.hasAttribute("data-default-display")&&(a.style.display=a.getAttribute("data-default-display"),a.removeAttribute("data-default-display"))}delete c.d[b];
delete c.c[b];delete c.h[b]}};this.$=function(b){s("server request sent: "+b.sectionId);var d,a,k,e=n.document;a=c.oa(b);s("Ad server full URL: "+a);b.__window&&b.__window.document&&(e=b.__window.document);if(!0===c.w(x(b.sectionId,b.instance)))return a='<script type="text/javascript" src="{{url}}">\x3c/script>'.replace("{{url}}",a),e.write(a),n.__putPixel(300500,b.sectionId?b.sectionId:!1),!0;d=e.createElement("script");d.async=!0;d.type="text/javascript";d.src=a;k=e.getElementsByTagName("script")[0];
c.ya()?setTimeout(function(){k.parentNode.insertBefore(d,k);n.__putPixel(300500,b.sectionId?b.sectionId:!1)},0):(k.parentNode.insertBefore(d,k),n.__putPixel(300500,b.sectionId?b.sectionId:!1));return!0};this.U=function(){c.j&&(clearTimeout(c.j),c.j=!1);if(0==c.p.length){var b=G;b&&""!==b+""&&(b=(b=document.cookie.match(b+"=([^;]*)"))&&unescape(b[1])||!1,c.p=b&&b.split(",")||[])}b=c.r;c.r={};for(var d in b){var a=b[d];b.hasOwnProperty(d)&&"function"===typeof a&&a.call()}};this.X=function(b,d,a,k,e){var f=
b.size;c.o(f)&&(f=f.split(c.Ka));a={a:d,C:a,b:k,data:b.data,type:b.type||"",size:f,A:b.noad,k:e,V:b.passback_url,t:b.dynamic_height};!b.hasOwnProperty("dynamic_height")&&this.c[a.b]&&this.c[a.b].hasOwnProperty("dynamic_height")&&(a.t=this.c[a.b].dynamic_height);(d=c.h[k]&&c.h[k].m&&c.h[k].m[d])&&b.hb&&d.bidder===b.hb&&(a.N=d.adId,a.size=d.size.split("x"));c.d[a.b]=c.d[a.C]||{};return c.d[a.b][a.a]=a};this.D=function(b){var d=arguments[arguments.length-1];"object"===typeof d&&(d=void 0);var a,k,e;
k=!1;b&&0<b.length&&b[0].section_id&&(k=b[0].section_id);n.__putPixel(300600,k);if(b&&b.length){e=b[0]&&b[0].section_id+(d?"_"+d:"");var f=!this.c[e]||!1!==this.c[e].__autoRender;c.d=c.d||{};for(var g=0,h=b.length;g<h;g++)if(a=b[g],k=d?q+a.id+r+a.section_id+r+d:q+a.id+r+a.section_id,a=c.X(a,k,a.section_id,e,a.subs),f||this.ea[k])c.ma(k,a.C,d,c.F[k],a),delete c.F[k]}};this.oa=function(b){b=b||{};if(b.sectionId){var d="https:"===document.location.protocol,a,k,e,f=[],g,h,l,m,w,p,s,q,r,z,v,t,y=n;l=this.sa();
var u=this.v;e="section_id cache_safe ad_server_url handler_name handler handler_scope tz fl click3rd seg is_secure ord pid ad_preview_li_id format".split(" ");m=this.Fa()||{};if(b.ad_server_url)if("string"===typeof b.ad_server_url&&b.ad_server_url.match(/^(?:https?:)?\/\//i))a=b.ad_server_url,t=!0;else throw Error('"ad_server_url" must be correct URL string.');a||(t=!1,a=m.ad_preview_li_id?L:M);h=b.handler;p=b.handler_scope;s=b.sectionId;q=b.instance;r=x(s,q);b.__window&&(y=b.__window);h&&("function"===
typeof h?z=h:"function"===typeof y[h]&&(z=y[h]));z?"object"!==typeof p&&(p={D:function(){return c.D.apply(c,arguments)}}):(h=!1,z=this.D,p=this);w=N+"_"+r;y[w]=function(){try{delete y[w]}catch(a){y[w]=void 0}Array.prototype.push.call(arguments,q);z.apply(p,arguments)};a=a.replace(/^https?:|\?$|\&$/img,"");a=(d?"https:":"http:")+a;v=-1<a.indexOf("?");g=["section_id="+s,"handler_name="+w,"tz="+(new Date).getTimezoneOffset(),"fl="+c.qa(),"is_secure="+(d?1:0)];if(b.cache_safe){H&&((new Image).src=(d?
"https:":"http:")+H+"?"+["section_id="+encodeURIComponent(s),"ord="+Math.floor(1E13*Math.random())].join("&"));if(!t)throw Error('If "cache_safe" == true, then "ad_server_url" must be also defined.');d=v?"&":"?";g.push("cache_safe=1")}else d=(v?"&":"?")+"ord="+Math.floor(1E13*Math.random())+"&",g.push("pid="+c.Ha+(b.pageIdModifier?"-"+encodeURIComponent(b.pageIdModifier):""));m.ad_preview_li_id&&g.push("ad_preview_li_id="+m.ad_preview_li_id);if((m=b.format)&&"jsonp"!==m)if(h)g.push("format="+m);else throw Error('If "format" has another value that "jsonp", then "handler_name" must be also defined.');
f=f.concat(g);h=(this.c[r]||{}).custom;g={};for(k in u)u.hasOwnProperty(k)&&(g[k]=u[k]);for(k in h)h.hasOwnProperty(k)&&(g[k]=h[k]);f=c.J(g,f,e);f=c.ja(f,b.slot_sizes);b.dmp&&c.K&&(f=c.J(c.K,f,e));(k=(this.c[r]||{}).click3rd)&&f.push("click3rd="+k);!1!==l&&f.push("lang="+encodeURIComponent(l));l=c.p;b.dmp&&"undefined"!==typeof l&&0<l.length&&(b="",b=c.za(a,f,"seg="+l.join("_")),f.push(b));return a+=d+f.join("&")}};this.ja=function(b,d){var a=c.ta();b.push("vpsz="+a.width+"x"+a.height);if(c.isArray(d)){for(var k,
e,f=[],g,h,l=d.length;l--;)if(h=d[l]&&d[l].viewports,c.isArray(h)&&h.length&&d[l].id){k=-1;e=[];for(g=h.length;g--;)h[g].minwidth>k&&h[g].minwidth<=a.width&&(k=h[g].minwidth,e=h[g].sizes);f.push('{"id":"'+d[l].id+'","sizes":['+(e.length?'"'+e.join('","')+'"':"")+"]}")}f.length&&b.push("adszs="+encodeURIComponent("["+f.join(",")+"]"))}return b};this.Fa=function(){var b,d,a;b={};a=document.location.href;a=a.split("?")[1];if(!a)return b;try{a=a.split("&")}catch(c){return b}for(var e=0;e<a.length;e++){d=
a[e]||"";try{d=d.split("=")}catch(f){d=[]}this.f(d[0])&&(b[d[0]]=d[1])}return b};this.za=function(b,d,a){if(2E3>=(b+"&"+d.join("&")+a).length)return a;b=b+"&"+d.join("&");a=a.split("_");for(d=0;2E3<(b+a.join("_")).length&&1E4>d;)a.pop(),d++;return a.join("_")};this.J=function(b,d,a){b=b||{};d=d||[];a=a||[];var k,e;a:for(e in b){k=0;for(var f=a.length;k<f;k++)if(a[k]+""===e+"")continue a;if(b.hasOwnProperty(e)){k=b[e];if(c.isArray(k)){d.push(e+"="+encodeURIComponent(k.join()));continue a}d.push(e+
"="+encodeURIComponent(k))}}return d};this.Ga=function(b){var d=r||"_";return b.replace(q,"").split(d)};this.u=function(b,d,a){c.d=c.d||{};var k,e=r||"_";c.f(d)||(k=b.replace(q,"").split(e),d=k[1],c.f(a)&&k[2]!==a?(k[2]=a,b=q+k.join(e)):a=k[2]);d=x(d,a);return c.d[d]&&c.d[d][b]};this.ba=function(b,d){c.f(b)&&(c.i[d.b]=c.i[d.b]||{},b?c.i[d.b][d.a]=!0:delete c.i[d.b][d.a])};this.da=function(b){var d,a;a=b.b;b=b.a;try{d=!!c.i[a][b]}catch(k){d=!1}return d};this.sa=function(){for(var b=document.getElementsByTagName("meta"),
d,a=!1,c=0;c<b.length;c++)if(d=!1,b[c]&&(d=b[c].getAttribute("http-equiv")||b[c].httpEquiv),d&&"content-language"===d.toLowerCase()){a=(a=b[c].getAttribute("content")||b[c].content)||!1;break}return a}}function E(m){function c(a,b,d){a=a.childNodes;var f=a.length,g=0,h=0,l,n={T:0,fa:0};d=[].concat(d||[]);for(b=b||{x:0,y:0};f--;)if(l=a[f],l.childNodes.length||l.offsetWidth||l.offsetHeight){for(h=d.length;h--;)if(d[h].Ca===l.offsetParent){n=d[h].Da;break}g=n.T+l.offsetLeft;h=n.fa+l.offsetTop;d.push({Ca:l,
Da:{T:g,fa:h}});h+=l.offsetHeight;g+=l.offsetWidth;c(l,b,d);b.x=Math.max(b.x,g);b.y=Math.max(b.y,h)}return b}function b(a,b){var e;e=(b||(a.contentWindow?a.contentWindow.document:a.contentDocument)).body;if(9>d.l())return c(e);var f=e.style.position;e.style.position="absolute";var g={x:e.offsetWidth,y:e.offsetHeight};e.style.position=f;return g}var d=this;m instanceof u&&(this.ia=m);this.Y=function(a,b,c){if(!a||!a.a)return s("Calling renderSlot without slot definition argument is not allowed"),!1;
var f=A(c),g=f.s;c=f.ha;var h,l,m,w,q,r,f=g.getElementById(a.a);if(!f)return s("Not ready to render: "+a.a),!1;if(a.N&&n.pbjs&&"function"===typeof pbjs.renderAd)g=d.W(a,g),g.src="javascript:\"<html><body style='background:transparent;margin:0%;'></body></html>\"",f.innerHTML="",f.appendChild(g),h=g.contentWindow?g.contentWindow.document:g.contentDocument,pbjs.renderAd(h,a.N);else{c.__asl__adjustHeight=c.__asl__adjustHeight||d.La;m=a.type||"html";q=parseInt(a.size[0],10);r=parseInt(a.size[1],10);w=
(0!==q||0!==r)&&a.t;if("javascript"===m&&d.w(a.b)){l='<script type="text/javascript">'+a.data+"\x3c/script>";g.write(l);if(a.A&&(f.setAttribute("data-default-display",f.style.display),f.style.display="none",c[p+"OnNoad"]))c[p+"OnNoad"](a.a);if(c[p+"OnRenderStart"])c[p+"OnRenderStart"]({x:q,y:r},a.a);try{w?c.__asl__adjustHeight(null,a.a,!0):d.G(c,null,a.a)}catch(v){s("Resize fail"+v)}s("Filled content on: "+a.a+" with "+a.type+" content");return!0}g=d.W(a,g);g.src="javascript:\"<html><body style='background:transparent;margin:0%;'></body></html>\"";
b||(f.innerHTML="");f.appendChild(g);0===d.l()||a.xa||(a.data=d.ua(a.data),a.xa=!0);b='<script type="text/javascript">var addEvent = '+this.n+';addEvent(window, "load", invokeResize, true);function invokeResize(){try{window.parent["__asl__adjustHeight"]("'+g.id+'","'+a.a+'");}catch(err){}}\x3c/script>';switch(m){case "javascript":l='<html><body style=\'background:transparent;margin:0%;\'><script type="text/javascript">var inDapIF=true;\x3c/script><script type="text/javascript">'+a.data+"\x3c/script>"+
(w?b:"")+"</body></html>";break;case "html":l=a.data}b=d.S();h=g.contentWindow?g.contentWindow.document:g.contentDocument;0!==d.l()||b?(h=c.frames[g.name],h.contents=l,h.location.replace(d.pa(a))):(-1!==navigator.userAgent.indexOf("Firefox")&&h.open("text/html","replace"),h.write(l),h.close());if(a.A&&(f.setAttribute("data-default-display",f.style.display),f.style.display="none",c[p+"OnNoad"]))c[p+"OnNoad"](a.a);if(c[p+"OnRenderStart"])c[p+"OnRenderStart"]({x:q,y:r},a.a);s("Filled content on: "+a.a+
" with "+a.type+" content");if("html"===m&&w){var t=g.name,u=g.id;0!==d.l()||b?setTimeout(function(){d.I(t,u,a.a,c)},b?1E3:100):this.I(t,u,a.a,c)}else this.G(c,g,a.a);return!0}};this.n=function(a,b,d,c,g){a.addEventListener?a.addEventListener(b,d,c):(g=g||n,a.attachEvent("on"+b,function(){return d.call(a,g.event)}))};this.I=function(a,b,d,c){function g(){if(!m){m=!0;try{l.id!==b&&l.id==="dead_"+b?l.parentNode&&l.parentNode.removeChild(l):h.__asl__adjustHeight(b,d)}catch(a){n.__ASL_DEBUG&&console.error(a)}}}
c=c||n;a=c.frames[a];var h=c,l=c.document.getElementById(b),m=!1;this.n(a,"load",g,!0,c);l&&this.n(l,"load",g,!0,c);try{a&&a.document&&"complete"===a.document.readyState&&g()}catch(p){n.__ASL_DEBUG&&console.error(p)}};this.W=function(a,b){b=b||document;var c=b.createElement("iframe"),f="border:none;",g=d.ra(a.a);d.o(a.size[0])&&(f+="width:"+a.size[0]+"px;",c.width=a.size[0]);d.o(a.size[1])&&(f+="height:"+a.size[1]+"px;",c.height=a.size[1]);"0"===a.size[0]&&"0"===a.size[1]&&(f+="display:none;");c.setAttribute("style",
f);c.setAttribute("frameBorder","0");c.setAttribute("scrolling","no");c.name=g;c.id=g;return c};this.pa=function(a){return d.S()&&!d.w(a.b)?"javascript:document.write(window.contents);":"javascript:window.contents"};this.ra=function(a){return"fif_slot_"+q+"_"+a};this.La=function(a,b){var c,f,g,h,l;c=d.ia.u(b);f=this.document.getElementById(a);g=this.document.getElementById(b);f&&g&&(l=d.L(f),h=d.M(f,this),(c.t||0===parseInt(c.size[1],10))&&!isNaN(h.y)&&l.y>h.y&&(f.style.height=l.y+"px",f.setAttribute("height",
l.y),d.f(g.style.height)&&(g.style.height=l.y+"px")),0===parseInt(c.size[0],10)&&!isNaN(h.x)&&l.x>h.x&&(f.style.width=l.x+"px",f.setAttribute("width",l.x),g.style.width=l.x+"px"),f.style.display="block",d.G(this,f,b))};this.G=function(a,c,e){a=a||n;var f;try{if(a.parent!==a&&a.inDapIF&&a.frameElement&&"iframe"===(a.frameElement.tagName+"").toLowerCase()){var g=a.frameElement,h=d.L(g),l=d.M(g,a);isNaN(l.y)||(f=b(g),f.y<l.y?(g.style.height=f.y+"px",g.setAttribute("height",f.y)):h.y>l.y&&(g.style.height=
h.y+"px",g.setAttribute("height",h.y)));isNaN(l.x)||(f=f||b(g),f.x<l.x?(g.style.width=f.x+"px",g.setAttribute("width",f.x)):h.x>l.x&&(g.style.width=h.x+"px",g.setAttribute("width",h.x)))}}catch(m){}a[p+"OnRenderEnd"]&&(f=f||b(null,a.document),a[p+"OnRenderEnd"]({x:f.x,y:f.y},c&&{x:c.offsetWidth,y:c.offsetHeight},e))};this.L=function(a){var b,c;b=a.contentWindow?a.contentWindow.document:a.contentDocument;a=b.body;c=6>d.l()?a:b.documentElement;b=Math.max(a.scrollHeight,a.offsetHeight,c.clientHeight,
c.scrollHeight,c.offsetHeight);return{x:Math.max(a.scrollWidth,a.offsetWidth,c.clientWidth,c.scrollWidth,c.offsetWidth),y:b}};this.M=function(a,b){b=b||n;var c,d;c=(d=b.getComputedStyle?a.ownerDocument.defaultView.opener?a.ownerDocument.defaultView.getComputedStyle(a,null):b.getComputedStyle(a,null):a.currentStyle||{})?d.height:a.style.height;c=parseInt(c,10);d=d?d.width:a.style.width;d=parseInt(d,10);return{x:d,y:c}}}function O(){var m=this;this.c={};this.B=null;this.Ka="x";Function.prototype.bind||
(Function.prototype.bind=function(c){function b(){return k.apply(this instanceof d?this:c,a.concat(Array.prototype.slice.call(arguments)))}function d(){}if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var a=Array.prototype.slice.call(arguments,1),k=this;d.prototype=this.prototype;b.prototype=new d;return b});this.qa=function(){var c=0,b;if(m.f(navigator.plugins)&&"object"===typeof navigator.plugins["Shockwave Flash"])!(b=navigator.plugins["Shockwave Flash"].description)||
m.f(navigator.mimeTypes)&&navigator.mimeTypes["application/x-shockwave-flash"]&&!navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(b=b.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),c=parseInt(b.replace(/^(.*)\..*$/,"$1"),10));else if(m.f(n.ActiveXObject))try{var d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");d&&(b=d.GetVariable("$version"))&&(b=b.split(" ")[1].split(","),c=parseInt(b[0],10))}catch(a){}return c};this.ta=function(){if(!this.B){var c=0,b=0;"number"===typeof n.innerHeight?
(c=n.innerHeight,b=n.innerWidth):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(c=document.documentElement.clientHeight,b=document.documentElement.clientWidth):document.body&&(document.body.clientWidth||document.body.clientHeight)&&(c=document.body.clientHeight,b=document.body.clientWidth);this.B={width:b,height:c}}return this.B};this.f=function(c){return"undefined"!==typeof c};this.o=function(c){return m.f(c)&&null!==c&&""!==c+""};this.w=
function(c){return m.c&&m.c[c]&&m.c[c].sync};this.l=function(){var c=navigator.userAgent,b=c.indexOf("MSIE ");return-1===b?0:parseFloat(c.substring(b+5,c.indexOf(";",b)))};this.S=function(){var c=navigator.userAgent;return null!==c.match(/\d\sNavigator\/\d/)||null!==c.match(/\d\sNetscape\/\d/)};this.ya=function(){return-1!==navigator.userAgent.indexOf("Opera")};this.isArray=function(c){return"[object Array]"===Object.prototype.toString.call(c)};this.ua=function(c){n.R=n.R||{};c+="";for(var b=[],d=
n.R,a=0;a<c.length;a++){var k=c.charAt(a),e=k.charCodeAt(0),f=a+1;if(8>e||127<e)k in d?k=d[k]:(e="&#x"+("000"+e.toString(16)).slice(-4)+";",k=d[k]=e);b[f]=k}return b.join("")};this.na=function(){var c=this.hash;return c()+c()+c()+c()+c()+c()+c()};this.hash=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}}function A(m){var c;try{m?c=m.document:(c=document,m=n)}catch(b){c=document,m=n}return{ha:m,s:c}}function x(m,c){var b;return m+(c?(b||"_")+c:"")}function s(m){n.__ASL_DEBUG&&
"undefined"!==typeof console&&console.info&&console.info(new Date," -> ",m.replace("http","htt_p"))}function I(m){function c(){d||(d=setInterval(function(){var a,c,e=0,f;for(f in b)if(e++,b.hasOwnProperty(f+"")){var g=b[f];if(3!=g.state){var h=g,l=n.document,p=l.getElementById(h.a);if(p){a=p;var q=0;c=0;do q+=a.offsetTop||0,c+=a.offsetLeft||0,a=a.offsetParent;while(a);q=a=q;a=p.offsetWidth?p.offsetWidth:1;var p=p.offsetHeight?p.offsetHeight:1,r=q+p;c=Math.max(0,Math.min(a,(n.pageXOffset||l.documentElement.scrollLeft)+
(n.innerWidth||l.documentElement.clientWidth)-c,c+a-(n.pageXOffset||l.documentElement.scrollLeft)));l=Math.max(0,Math.min(p,(n.pageYOffset||l.documentElement.scrollTop)+(n.innerHeight||l.documentElement.clientHeight)-q,r-(n.pageYOffset||l.documentElement.scrollTop)));l=c*l/(a*p);0==h.state&&(1==p||l>=h.g)?(s(h.a+" first time inview."),h.state=1):1==h.state&&(l<h.g||0>=l&&1==p)?(s(h.a+" outview after first inview."),h.state=2):2==h.state&&(l>=h.g||0<l&&1==p)&&(s(h.a+" inview again. reload..."),h.state=
3)}else delete b[h.b];3==g.state&&m.aa(g.Z)}}0==e&&d&&(clearInterval(d),d=!1)},100))}var b={},d=!1;this.wa=function(a,d){if(!d.viewable||!d.viewable.slot||b[a])return!1;var e={};e.a=q+d.viewable.slot+r+a;e.b=a;e.reload=parseInt(d.viewable.reload,10);e.reload=isNaN(e.reload)?!0:1<e.reload?e.reload:1;e.ca=0;e.g=parseFloat(d.viewable.percent)||0.5;0>=e.g?e.g=1E-11:1<e.g&&(e.g=1);e.state=2;e.Z=d;b[a]=e;c();return!0};this.ga=function(a){if(a&&a.b&&m.c[a.b]&&b[a.b]){var d=m.c[a.b];if(d.viewable){var e=
b[a.b];e.ca++;a.A||!0!==e.reload&&e.ca>=e.reload?delete b[a.b]:(e.state=0,e.Z=d,delete m.c[a.b],b[a.b]=e,c())}}}}n.__putPixel=n.__putPixel||function(){};n.__putPixel(300300);var v="__ASL__";if("undefined"===typeof n[v]){var M="//nkis.nikkei.com/ad",L="//nkis.nikkei.com/ad_preview",H="",N="process_tag_provider_response",q="",r="_",p="TagProvider",F="https://nkispa.nikkei.com",K="/fh/passback_d094700e.html",B="passbackReceiverIFrame";if("undefined"!==
typeof n.showadAMPAdapter){n[p]={displayAd:function(){},requestAds:function(m){n[v].requestAds(m)}};var t="sectionId instance custom adServerUrl cacheSafe pageIdModifier click3rd".split(" "),P={adServerUrl:"ad_server_url",cacheSafe:"cache_safe"};n.showadAMPAdapter.inited=!0;n.showadAMPAdapter.registerSlot=function(m,c){for(var b=m.slot,d={},a=t.length;a--;)m.hasOwnProperty(t[a])&&(d[P[t[a]]||t[a]]=m[t[a]]);m.custom&&(d.custom=JSON.parse(m.custom));d.__autoRender=!1;b=d.instance?q+b+r+d.sectionId+
r+d.instance:q+b+r+d.sectionId;if(c&&c.context){a=c.document.createElement("div");a.id=b;var k=c.document.getElementById("c");k?k.appendChild(a):c.document.body.appendChild(a);d.__window=c;"function"===typeof c.context.renderStart&&(c[p+"OnRenderStart"]=function(a){c.context.renderStart({width:a.x,height:a.y})});"function"===typeof c.context.requestResize&&(c[p+"OnRenderEnd"]=function(a,b){c.context.requestResize(b.x,b.y)});"function"===typeof c.context.noContentAvailable&&(c[p+"OnNoad"]=function(){c.context.noContentAvailable()})}n[p].requestAds(d);
n[p].displayAd(b,d.sectionId,d.instance,c)}}if("undefined"===typeof n[p])n.__putPixel(300666,!1,"Global linking has failed");else{var C="//nkispa.nikkei.com/fh/dmp_plugin_aone_d094700e.js",G="a1_segment_ids",J="500";u.prototype=new O;E.prototype=u.prototype;var D=new u(n[p]);D.Aa();n[v]=D;D.Ia()}}})(window);
